### ISSUE TITLE
Can not open discord in README.md

### ISSUE THREAD

**Issue by shadowings-zy** [Devographics/locale-en-US#17]
The Discord invite link in README.md (https://discord.com/invite/zRDb35jfrt) seems expired.
I suppose we need to update it.

<img width="849" alt="截屏2022-01-18 18 08 25" src="https://user-images.githubusercontent.com/29225966/149916342-d33b4347-276d-45b6-8cd5-eead0824798d.png">

**Comment by Klrfl** [comment]
The link has been updated since then I think, I just joined the Discord server myself. I suppose you can close this issue now.
