### ISSUE TITLE
Some links in the README.md not working

### ISSUE THREAD

**Issue by Klrfl** [Devographics/locale-en-US#29]
I am trying to translate the site into id-ID and following the guide in this repo's README.md, I followed the link to the GraphQL IDE and also the [link to credit the translator names](https://github.com/devographics/monorepo/blob/main/api/src/data/locales.yml).

Both don't work: the GraphQL IDE was always returning NetworkError, and while there was [another GraphQL IDE](https://graphiql.stateofjs.com/) the query for `untranslatedKeys` always returns null; the link to credit the translator names is currently nonexistent as the file was moved (or removed idk). Please update the links.

**Comment by SachaG** [comment]
Thanks for letting me know!

**Comment by Klrfl** [comment]
Fixed
